In [3]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
import matplotlib as mpl

# 그래프 설정
sns.set()

# 폰트 설정
mpl.rcParams['font.family'] = 'NanumGothic'
mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14

In [4]:
# 파일 불러오기
df = pd.read_parquet('/content/drive/MyDrive/11_파이널프로젝트관련/file/채널정보_세그먼트.ipynb')

# 컬럼이 생략되지 않도록 출력 옵션 설정
pd.set_option('display.max_columns', None)  # 컬럼 모두 출력
pd.set_option('display.width', None)        # 가로 너비 제한 해제
pd.set_option('display.max_colwidth', None) # 컬럼 내용 길이 제한 해제

# 데이터 상위 5개 행 출력
df.head()

ID Segment    기준년월 인입횟수_ARS_R6M 이용메뉴건수_ARS_R6M  인입일수_ARS_R6M  \
0  TRAIN_000000       D  201807       10회 이상         10회 이상             8   
1  TRAIN_000000       D  201808       10회 이상         10회 이상             9   
2  TRAIN_000000       D  201809       10회 이상         10회 이상             9   
3  TRAIN_000000       D  201810       10회 이상         10회 이상             9   
4  TRAIN_000000       D  201811       10회 이상         10회 이상            10   

   인입월수_ARS_R6M  인입후경과월_ARS  인입횟수_ARS_B0M  이용메뉴건수_ARS_B0M  인입일수_ARS_B0M  \
0             6           0             2               6             2   
1             6           0             2               6             2   
2             6           0             2               6             2   
3             6           0             2               6             2   
4             6           0             2               6             2   

  방문횟수_PC_R6M 방문일수_PC_R6M  방문월수_PC_R6M  방문후경과월_PC_R6M 방문횟수_앱_R6M  방문일수_앱_R6M  \
0       1회 이상       1회 이상            0              6      1회 이상           0   
1       1회 이상       1회 이상            0              6      1회 이상           0   
2       1회 이상       1회 이상            0              6      1회 이상           0   
3       1회 이상       1회 이상            0              6      1회 이상           0   
4       1회 이상       1회 이상            0              6      1회 이상           0   

   방문월수_앱_R6M  방문후경과월_앱_R6M  방문횟수_모바일웹_R6M  방문일수_모바일웹_R6M  방문월수_모바일웹_R6M  \
0           0             6              0              0              0   
1           0             6              0              0              0   
2           0             6              0              0              0   
3           0             6              0              0              0   
4           0             6              0              0              0   

   방문후경과월_모바일웹_R6M  방문횟수_PC_B0M  방문일수_PC_B0M  방문횟수_앱_B0M  방문일수_앱_B0M  \
0                6            0            0           0           0   
1                6            0            0           0           0   
2                6            0            0           0           0   
3                6            0            0           0           0   
4                6            0            0           0           0   

   방문횟수_모바일웹_B0M  방문일수_모바일웹_B0M  인입횟수_IB_R6M  인입횟수_금융_IB_R6M  인입일수_IB_R6M  \
0              0              0            1               0            1   
1              0              0            1               0            2   
2              0              0            2               0            2   
3              0              0            2               0            2   
4              0              0            2               0            2   

   인입월수_IB_R6M  이용메뉴건수_IB_R6M  인입후경과월_IB_R6M  인입횟수_IB_B0M  인입일수_IB_B0M  \
0            1              1              4            0            0   
1            1              1              5            0            0   
2            1              1              6            0            0   
3            1              1              6            0            0   
4            1              1              6            0            0   

   이용메뉴건수_IB_B0M  인입불만횟수_IB_R6M  인입불만일수_IB_R6M  인입불만월수_IB_R6M  \
0              0              0              0              0   
1              0              0              0              0   
2              0              0              0              0   
3              0              0              0              0   
4              0              0              0              0   

   인입불만후경과월_IB_R6M  인입불만횟수_IB_B0M  인입불만일수_IB_B0M  상담건수_B0M  IB문의건수_사용승인내역_B0M  \
0                6              0              0         0                  0   
1                6              0              0         0                  0   
2                6              0              0         0                  0   
3                6              0              0         0                  0   
4                6      

In [5]:
# 결측치 확인
df.isna().sum()

ID                      0
Segment                 0
기준년월                    0
인입횟수_ARS_R6M            0
이용메뉴건수_ARS_R6M          0
                   ...   
OS구분코드            1633566
홈페이지_금융건수_R6M           0
홈페이지_선결제건수_R6M          0
홈페이지_금융건수_R3M           0
홈페이지_선결제건수_R3M          0
Length: 106, dtype: int64

In [6]:
# 고유값 개수 확인
single_value_cols = []
print("\n--- 고정된 값 확인 ---")
for col in df.columns:
    unique_value_count = df[col].nunique(dropna=False)

    # 고유한 값의 개수가 1개인 경우
    if unique_value_count == 1:
        single_value_cols.append(col)

print(f"\n고정값 : \n{single_value_cols}")


# 컬럼 값이 완전히 동일한 중복 컬럼 찾기
# 병합 후 재실행
print("\n--- 중복 컬럼 확인 ---")
duplicated_cols = {}
cols = df.columns.tolist()
for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        col1 = cols[i]
        col2 = cols[j]
        if df[col1].equals(df[col2]):
            if col1 not in duplicated_cols:
                duplicated_cols[col1] = []
            duplicated_cols[col1].append(col2)
if duplicated_cols:
    print(f"중복 컬럼들: \n{duplicated_cols}")


--- 고정된 값 확인 ---

고정값 : 
['인입횟수_금융_IB_R6M', '인입불만횟수_IB_R6M', '인입불만일수_IB_R6M', '인입불만월수_IB_R6M', '인입불만후경과월_IB_R6M', '인입불만횟수_IB_B0M', '인입불만일수_IB_B0M', 'IB문의건수_한도_B0M', 'IB문의건수_결제_B0M', 'IB문의건수_할부_B0M', 'IB문의건수_정보변경_B0M', 'IB문의건수_결제일변경_B0M', 'IB문의건수_명세서_B0M', 'IB문의건수_비밀번호_B0M', 'IB문의건수_SMS_B0M', 'IB문의건수_APP_B0M', 'IB문의건수_부대서비스_B0M', 'IB문의건수_포인트_B0M', 'IB문의건수_BL_B0M', 'IB문의건수_분실도난_B0M', 'IB문의건수_CA_B0M', 'IB상담건수_VOC_B0M', 'IB상담건수_VOC민원_B0M', 'IB상담건수_VOC불만_B0M', 'IB상담건수_금감원_B0M', 'IB문의건수_명세서_R6M', 'IB문의건수_APP_R6M', 'IB상담건수_VOC_R6M', 'IB상담건수_VOC민원_R6M', 'IB상담건수_VOC불만_R6M', 'IB상담건수_금감원_R6M', '불만제기건수_B0M', '불만제기건수_R12M', '당사PAY_방문횟수_B0M', '당사PAY_방문횟수_R6M', '당사PAY_방문월수_R6M']

--- 중복 컬럼 확인 ---
중복 컬럼들: 
{'인입횟수_금융_IB_R6M': ['인입불만횟수_IB_R6M', '인입불만일수_IB_R6M', '인입불만월수_IB_R6M', '인입불만횟수_IB_B0M', '인입불만일수_IB_B0M', 'IB문의건수_한도_B0M', 'IB문의건수_결제_B0M', 'IB문의건수_할부_B0M', 'IB문의건수_정보변경_B0M', 'IB문의건수_결제일변경_B0M', 'IB문의건수_명세서_B0M', 'IB문의건수_비밀번호_B0M', 'IB문의건수_SMS_B0M', 'IB문의건수_APP_B0M', 'IB문의건수_부대서비스_B0M', 'IB문의건수_포인트

In [7]:
# 이상치 확인
df['IB문의건수_부대서비스_B0M'].unique()

array([0])

# 1. 📞 고객센터 채널 이용 행동 비교

In [8]:
# 1. 고객센터 채널 이용 행동 관련 컬럼
cols_1 = ['인입횟수_IB_R6M', '이용메뉴건수_IB_R6M', '상담건수_R6M']

# 세그먼트별 평균 계산
segment_means_1 = df.groupby('Segment')[cols_1].mean()
print("✅ 1. 고객센터 채널 이용 행동 - 세그먼트별 평균:\n")
print(segment_means_1)

✅ 1. 고객센터 채널 이용 행동 - 세그먼트별 평균:

         인입횟수_IB_R6M  이용메뉴건수_IB_R6M  상담건수_R6M
Segment                                      
A           2.155350       1.289095  2.320988
B           3.298611       1.750000  3.437500
C           1.772357       1.039274  1.869535
D           1.493978       0.891339  1.574604
E           0.846296       0.539781  0.900397


In [9]:
# 이상치 확인
df['인입불만횟수_IB_R6M'].unique()

array([0])

# 2. 🖥️ 디지털 채널 이용 성향

In [10]:
# 1. '1회 이상', '10회 이상' 등 텍스트를 숫자로 변환하는 함수
def convert_visit_counts(val):
    if isinstance(val, str):
        if val == '10회 이상':
            return 10
        elif val == '1회 이상':
            return 1
        elif val.isdigit():
            return int(val)
        else:
            return 0
    elif pd.isna(val):
        return 0
    else:
        return val

# 2. 사용할 컬럼 리스트
cols_2 = ['방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문횟수_모바일웹_R6M']

# 3. 각 컬럼에 변환 함수 적용
for col in cols_2:
    if col in df.columns:
        df[col] = df[col].apply(convert_visit_counts)

# 4. 세그먼트별 평균 계산
segment_means = df.groupby('Segment')[cols_2].mean()
print("✅ 세그먼트별 방문횟수 평균:\n", segment_means)

✅ 세그먼트별 방문횟수 평균:
          방문횟수_앱_R6M  방문횟수_PC_R6M  방문횟수_모바일웹_R6M
Segment                                        
A          1.397119     1.819959       0.229424
B          1.541667     1.500000       0.138889
C          1.372553     1.490078       0.180038
D          1.346333     1.379273       0.159127
E          1.234230     1.155030       0.064537


In [11]:
# 1. 앞서 사용한 방문횟수 변환 함수 (필요하면 다시 적용)
def convert_visit_counts(val):
    if isinstance(val, str):
        if val == '10회 이상':
            return 10
        elif val == '1회 이상':
            return 1
        elif val.isdigit():
            return int(val)
        else:
            return 0
    elif pd.isna(val):
        return 0
    else:
        return val

cols = ['방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문횟수_모바일웹_R6M']

for col in cols:
    if col in df.columns:
        df[col] = df[col].apply(convert_visit_counts)

# 2. 디지털 채널 방문횟수 합계 컬럼 생성
df['디지털채널_방문횟수_합계'] = df[cols].sum(axis=1)

# 3. 세그먼트별 평균 계산
segment_means_sum = df.groupby('Segment')['디지털채널_방문횟수_합계'].mean()
print("✅ 세그먼트별 디지털 채널 방문횟수 합계 평균:\n", segment_means_sum)

✅ 세그먼트별 디지털 채널 방문횟수 합계 평균:
 Segment
A    3.446502
B    3.180556
C    3.042668
D    2.884733
E    2.453796
Name: 디지털채널_방문횟수_합계, dtype: float64


In [12]:
# 이상치 확인
df['방문횟수_PC_R6M'].unique()

array([ 1, 10,  0])

# 3. ⏳ 경과월 관련 지표

In [25]:
cols_3 = ['인입후경과월_IB_R6M', '방문후경과월_앱_R6M', '불만제기후경과월_R12M']

segment_means_3 = df.groupby('Segment')[cols_3].mean()
print("✅ 3. 경과월 관련 지표 - 세그먼트별 평균:\n")
print(segment_means_3)

✅ 3. 경과월 관련 지표 - 세그먼트별 평균:

         인입후경과월_IB_R6M  방문후경과월_앱_R6M  불만제기후경과월_R12M
Segment                                            
A             4.291152      4.213992      10.148148
B             3.937500      2.180556      10.000000
C             4.531868      3.899843       9.237715
D             4.721571      4.009489       8.491144
E             5.201684      4.969703       6.041281


# 4. 🤬 불만 및 민원 제기 성향

In [24]:
cols_4 = ['IB상담건수_VOC불만_R6M', 'IB상담건수_금감원_R6M', '불만제기건수_R12M']

segment_means_4 = df.groupby('Segment')[cols_4].mean()
print("✅ 4. 불만 및 민원 제기 성향 - 세그먼트별 평균:\n")
print(segment_means_4)

✅ 4. 불만 및 민원 제기 성향 - 세그먼트별 평균:

         IB상담건수_VOC불만_R6M  IB상담건수_금감원_R6M  불만제기건수_R12M
Segment                                               
A                     0.0             0.0          0.0
B                     0.0             0.0          0.0
C                     0.0             0.0          0.0
D                     0.0             0.0          0.0
E                     0.0             0.0          0.0


# 5. 📲 OS 구분

In [15]:
# None (또는 NaN)인 행만 필터링
cols_5 = df[df['OS구분코드'].isnull()]

# 세그먼트별로 개수 집계
result = cols_5.groupby('Segment').size().reset_index(name='None_개수')

print(result)

  Segment  None_개수
0       A      438
1       B       36
2       C    56460
3       D   162414
4       E  1414218


In [16]:
# 전체 기준: 세그먼트별 전체 건수
total_counts = df.groupby('Segment').size().reset_index(name='Segment수')

# None 기준: OS구분코드가 None인 행만 필터링
cols_5 = df[df['OS구분코드'].isnull()]
none_counts = cols_5.groupby('Segment').size().reset_index(name='None_건수')

# 병합하여 비율 계산
merged = pd.merge(total_counts, none_counts, on='Segment', how='left')
merged['None_건수'] = merged['None_건수'].fillna(0)  # None 없는 세그먼트는 0으로
merged['None_비율(%)'] = ((merged['None_건수'] / merged['Segment수']) * 100).round(2)

print(merged)

  Segment  Segment수  None_건수  None_비율(%)
0       A       972      438       45.06
1       B       144       36       25.00
2       C    127590    56460       44.25
3       D    349242   162414       46.50
4       E   1922052  1414218       73.58


In [20]:
cols_6 = ['IB문의건수_포인트_R6M', 'IB문의건수_부대서비스_R6M']

segment_means_4 = df.groupby('Segment')[cols_6].sum()
print("✅ 4. 인터넷뱅킹 포인트 문의건수:\n")
print(segment_means_4)

✅ 4. 인터넷뱅킹 포인트 문의건수:

         IB문의건수_포인트_R6M  IB문의건수_부대서비스_R6M
Segment                                  
A                     0                 0
B                     0                 0
C                    29                 0
D                    11                 0
E                    11                25


In [21]:
cols_7 = ['IB문의건수_SMS_R6M', 'IB문의건수_APP_R6M']

segment_means_7 = df.groupby('Segment')[cols_7].sum()
print("✅ 4. 인터넷뱅킹 포인트 문의건수:\n")
print(segment_means_7)

✅ 4. 인터넷뱅킹 포인트 문의건수:

         IB문의건수_SMS_R6M  IB문의건수_APP_R6M
Segment                                
A                     0               0
B                     0               0
C                     0               0
D                     0               0
E                  1394               0
